---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "arcadedb.fullname" . }}
  labels:
    {{- include "arcadedb.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
data:
  rootPassword: {{ .Values.credentials.rootPassword | b64enc }}