apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcadedb.fullname" . }}
  labels:
    {{- include "arcadedb.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
  {{- if .Values.service.gremlinPort }}
    - name: gremlin
      port: {{ .Values.service.gremlinPort }}
      targetPort: gremlin
      protocol: TCP
  {{- end}}
  selector:
    {{- include "arcadedb.selectorLabels" . | nindent 4 }}
